global_costmap:
   global_frame: map
   robot_base_frame: agv_base_footprint
   update_frequency: 10.0
   publish_frequency: 10.0
   width: 20.0
   height: 20.0
   resolution: 0.05
   static_map: true
   rolling_window: false
